---
roles:
  - name: chrisvanmeer.dotfiles
  - name: chrisvanmeer.hashicorp
  - name: diodonfrost.vagrant
  - name: geerlingguy.apache
  - name: geerlingguy.certbot
  - name: geerlingguy.docker
  - name: geerlingguy.mysql
  - name: geerlingguy.ntp
  - name: geerlingguy.php
  - name: geerlingguy.php-mysql
  - name: geerlingguy.php-versions
  - name: geerlingguy.postfix
  - name: geerlingguy.security
  - name: oefenweb.ufw
