---
- hosts: localhost
  connection: local
  become: true

  vars:
    _ubuntu_major_version: 20

    apache_listen_ip: "127.0.0.1"
    apache_listen_port: 80
    apache_listen_port_ssl: 443

    php_version: "8.1"
    php_packages:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "libapache2-mod-php{{ php_version }}"
    php_enable_apc: false

    ntp_timezone: "Europe/Amsterdam"

    security_ssh_port: 22

    ufw_rules:
      - rule: allow
        to_port: "{{ security_ssh_port }}"
        protocol: tcp
        comment: "Allow incoming SSH"

    ppa_repos:
      - "ppa:agornostal/ulauncher"

    xtra_apt_packages:
      - alpine
      - ansible-lint
      - apticron
      - atop
      - bsdgames
      - build-essential
      - certbot
      - curl
      - ddgr
      - flameshot
      - git
      - gimp
      - gitsome
      - gnome-tweak-tool
      - google-chrome-stable
      - googler
      - htop
      - iperf3
      - less
      - lynx
      - mailutils
      - mc
      - multitail
      - nano
      - neofetch
      - net-tools
      - nload
      - screen
      - telnet
      - tilix
      - tmux
      - ulauncher
      - vim
      - vlc
      - wget
      - whois
      - yamllint

    xtra_snap_packages:
      - beekeeper-studio
      - bpytop
      - mattermost-desktop
      - multipass
      - remmina
      - simplenote
      - telegram-desktop

    xtra_classic_snap_packages:
      - code
      - sublime-text

  pre_tasks:
    - name: check | Fail when Linux distribution does not match
      fail:
        msg: "Failed, this is not Ubuntu 20...but {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
      when: (ansible_distribution != "Ubuntu") and (ansible_distribution_major_version|int != _ubuntu_major_version|int)
      tags: check

    - name: docker | Set a fact with the current user name to add it to the docker group later
      become: false
      set_fact:
        docker_users: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
      tags: docker, core

    - name: ssh | Ensure openssh-server is installed
      apt:
        name:
          - openssh-server
          - openssh-client
        state: present
      tags: ssh

    - name: ssh | Ensure openssh-server is started and enabled
      service:
        name: ssh
        state: started
        enabled: yes
      tags: ssh

  roles:
    - role: geerlingguy.certbot
      tags: certbot, core
    - role: geerlingguy.apache
      tags: apache, core
    - role: geerlingguy.php-versions
      tags: php, core
    - role: geerlingguy.php-mysql
      tags: php, core
    - role: geerlingguy.mysql
      tags: mysql, core
    - role: geerlingguy.docker
      tags: docker, core
    - role: geerlingguy.postfix
      tags: postfix, core
    - role: geerlingguy.security
      tags: security, core
    - role: geerlingguy.ntp
      tags: ntp, core
    - role: oefenweb.ufw
      tags: ufw, core

  tasks:

    - name: php-post | Remove standard index.html
      file:
        path: /var/www/html/index.html
        state: absent
      tags: php-post, core

    - name: php-post | Create Hello World PHP page
      copy:
        dest: /var/www/html/index.php
        content: "<?php echo 'Hello World!'; ?>"
      tags: php-post, core

    - name: hush | Check if .hushlogin exists
      stat:
        path: ~/.hushlogin
      become: false
      register: hush
      tags: hush, core

    - name: hush | Create a .hushlogin file if it not exists
      file:
        path: ~/.hushlogin
        state: touch
      become: false
      when: not hush.stat.exists
      tags: hush, core

    - name: apt-pre | Add needed PPA's
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop: "{{ ppa_repos }}"
      tags: apt-pre

    - name: "apt-pre | ensure Google linux signing key present"
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present
      tags: apt-pre

    - name: apt-pre | Add specified repository for Google Chrome
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
      tags: apt-pre

    - name: xtra | Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: xtra

    - name: xtra | Install the extra apt packages
      apt:
        name: "{{ xtra_apt_packages }}"
        state: present
      tags: xtra

    - name: xtra | Install the extra snap packages
      snap:
        name: "{{ xtra_snap_packages }}"
        classic: yes
        state: present
      tags: xtra, snap

    - name: xtra | Install the extra snap packages with classic parameter
      snap:
        name: "{{ xtra_classic_snap_packages }}"
        classic: yes
        state: present
      tags: xtra, snap-classic

    - name: apt-post | Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
      tags: apt-post

    - name: apt-post | Autoclean apt
      apt:
        autoclean: yes
      tags: apt-post

    - name: apt-post | Autoremove apt
      apt:
        autoremove: yes
      tags: apt-post

    - name: post | Check if a reboot is needed
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
      tags: post

  post_tasks:
    - name: post | Reboot warning if needed
      debug:
        msg: "Please reboot your system"
      when: reboot_required_file.stat.exists
      tags: post
