---
- hosts: localhost
  connection: local
  become: true

  vars:
    _ubuntu_major_version: 20

    apache_listen_ip: "127.0.0.1"
    apache_listen_port: 80
    apache_listen_port_ssl: 443

    php_version: "8.1"
    php_packages:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "libapache2-mod-php{{ php_version }}"
    php_enable_apc: false

    # firewall_allowed_tcp_ports:
    #   - "22"

    ntp_timezone: "Europe/Amsterdam"

    security_ssh_port: 22

    ufw_rules:
      - rule: allow
        to_port: "{{ security_ssh_port }}"
        protocol: tcp
        comment: "Allow incoming SSH"
      # - rule: allow
      #   to_port: "{{ apache_listen_port }}"
      #   protocol: tcp
      #   comment: "Allow incoming HTTP"
      # - rule: allow
      #   to_port: "{{ apache_listen_port_ssl }}"
      #   protocol: tcp
      #   comment: "Allow incoming HTTPS"

    xtra_packages:
      - alpine
      - apticron
      - atop
      - bsdgames
      - build-essential
      - certbot
      - curl
      - ddgr
      - git
      - gitsome
      - googler
      - htop
      - less
      - lynx
      - mailutils
      - nano
      - net-tools
      - nload
      - telnet
      - vim
      - wget

  pre_tasks:
    - name: Fail when Linux distribution does not match
      fail:
        msg: "Failed, this is not Ubuntu...but {{ ansible_distribution }}"
      when: ansible_distribution != "Ubuntu"

    - name: Fail when major OS version does not match
      fail:
        msg: "Failed, this is not Ubuntu 20...but {{ ansible_distribution_major_version }}"
      when: ansible_distribution_major_version|int != _ubuntu_major_version|int

    - name: Set a fact with the current user name to add it to the docker group later
      become: false
      set_fact:
        docker_users: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
      tags: docker

  roles:
    - role: geerlingguy.certbot
      tags: certbot
    - role: geerlingguy.apache
      tags: apache
    - role: geerlingguy.php-versions
      tags: php
    - role: geerlingguy.php-mysql
      tags: php
    - role: geerlingguy.mysql
      tags: mysql
    - role: geerlingguy.docker
      tags: docker
    - role: geerlingguy.postfix
      tags: postfix
    - role: geerlingguy.security
      tags: security
    # - role: geerlingguy.firewall
    #   tags: firewall
    - role: geerlingguy.ntp
      tags: ntp
    - role: oefenweb.ufw
      tags: ufw

  tasks:
    - name: Remove standard index.html
      file:
        path: /var/www/html/index.html
        state: absent
      tags: php-post

    - name: Create Hello World PHP page
      copy:
        dest: /var/www/html/index.php
        content: "<?php echo 'Hello World!'; ?>"
      tags: php-post

    - name: Hush all the login banner stuff
      file:
        path: ~/.hushlogin
        state: touch
      become: false
      tags: hush

    - name: Install the extra packages
      apt:
        name: "{{ xtra_packages }}"
        state: present
      tags: xtra

    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
      tags: apt

    - name: Autoclean apt
      apt:
        autoclean: yes
      tags: apt

    - name: Autoremove apt
      apt:
        autoremove: yes
      tags: apt

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
      tags: post

  post_tasks:
    - name: Reboot warning if needed
      debug:
        msg: "Please reboot your system"
      when: reboot_required_file.stat.exists
      tags: post
