---
- name: "Ubuntu 20.04 LTS Deployment"
  hosts: localhost
  connection: local
  become: true

  vars:
    # Major Ubuntu version to check against
    _ubuntu_major_version: 20

    # Apache variables
    apache_listen_ip: "127.0.0.1"
    apache_listen_port: 80
    apache_listen_port_ssl: 443

    # PHP variables
    php_version: "8.1"
    php_packages:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "libapache2-mod-php{{ php_version }}"
    php_enable_apc: false

    # NTP variables
    ntp_timezone: "Europe/Amsterdam"

    # Security variables
    security_ssh_port: 22
    ufw_rules:
      - rule: allow
        to_port: "{{ security_ssh_port }}"
        protocol: tcp
        comment: "Allow incoming SSH"

    # External PPA's
    ppa_repos:
      - "ppa:agornostal/ulauncher"

    # Variables for copy jobs
    home_path: "~"
    src_files: "src"
    dotfiles_files:
      - .hushlogin
      - .tmux.conf
      - .vimrc

    # Variables for bash
    bash_rc_path: "{{ home_path }}/.bashrc"
    bash_aliases:
      - alias: 'a1'
        command: 'sudo apt update'
      - alias: 'a2'
        command: 'sudo apt upgrade'
      - alias: 'a3'
        command: 'sudo apt dist-upgrade'
      - alias: 'a4'
        command: 'sudo apt autoremove'
      - alias: 'a5'
        command: 'sudo apt clean'
      - alias: 'mp'
        command: 'multipass'

    zsh_aliases_path: "{{ home_path }}/.zsh_aliases"
    zsh_aliases:
      - alias: 'a1'
        command: 'sudo apt update'
      - alias: 'a2'
        command: 'sudo apt upgrade'
      - alias: 'a3'
        command: 'sudo apt dist-upgrade'
      - alias: 'a4'
        command: 'sudo apt autoremove'
      - alias: 'a5'
        command: 'sudo apt clean'
      - alias: 'mp'
        command: 'multipass'

    # Package variables
    xtra_apt_packages:
      - alpine
      - ansible-lint
      - apticron
      - atop
      - bsdgames
      - build-essential
      - certbot
      - curl
      - ddgr
      - flameshot
      - git
      - gimp
      - gitsome
      - gnome-tweak-tool
      - google-chrome-stable
      - googler
      - htop
      - iperf3
      - less
      - lynx
      - mailutils
      - mc
      - mlocate
      - multitail
      - nano
      - neofetch
      - net-tools
      - nload
      - screen
      - telnet
      - tilix
      - tmux
      - ulauncher
      - vim
      - virtualbox
      - virtualbox-ext-pack
      - vlc
      - wget
      - whois
      - yamllint
    xtra_snap_packages:
      - beekeeper-studio
      - bpytop
      - mattermost-desktop
      - multipass
      - remmina
      - simplenote
      - telegram-desktop
    xtra_classic_snap_packages:
      - code
      - sublime-text

  pre_tasks:
    - name: "chrisvanmeer.check : Fail when Linux distribution does not match."
      fail:
        msg: "Failed, this is not Ubuntu 20...but {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
      when: (ansible_distribution != "Ubuntu") or (ansible_distribution_major_version|int != _ubuntu_major_version|int)
      tags: check

    - name: "chrisvanmeer.docker : Set a fact with the current user name to add it to the docker group later."
      become: false
      set_fact:
        docker_users: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
        current_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
      tags: docker, core

  roles:
    - role: geerlingguy.certbot
      tags: certbot, core
    - role: geerlingguy.apache
      tags: apache, core
    - role: geerlingguy.php-versions
      tags: php, core
    - role: geerlingguy.php-mysql
      tags: php, core
    - role: geerlingguy.mysql
      tags: mysql, core
    - role: geerlingguy.docker
      tags: docker, core
    - role: geerlingguy.postfix
      tags: postfix, core
    - role: geerlingguy.security
      tags: security, core
    - role: geerlingguy.ntp
      tags: ntp, core
    - role: oefenweb.ufw
      tags: ufw, core

  tasks:

    - name: "chrisvanmeer.openssh : Ensure openssh-server is installed."
      apt:
        name:
          - openssh-server
          - openssh-client
        state: present
      tags: openssh

    - name: "chrisvanmeer.openssh : Ensure openssh-server is started and enabled."
      service:
        name: ssh
        state: started
        enabled: yes
      tags: openssh

    - name: "chrisvanmeer.bash : Add bash aliases to {{ bash_rc_path }}."
      lineinfile:
        dest: "{{ bash_rc_path }}"
        line: 'alias {{ item.alias }}="{{ item.command }}"'
        regexp: "^alias {{ item.alias }}="
      become: false
      loop: "{{ bash_aliases }}"
      tags: bash, core

    - name: "chrisvanmeer.zsh : Ensure zsh is installed."
      apt:
        name: zsh
        state: present
      tags: zsh, core

    - name: "chrisvanmeer.zsh : Install oh-my-zsh."
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: ~/.oh-my-zsh
        force: yes
      become: false
      tags: zsh, core

    - name: "chrisvanmeer.zsh : Check if {{ zsh_aliases_path }} exists."
      stat:
        path: "{{ zsh_aliases_path }}"
      become: false
      register: zsh_aliases_status
      tags: zsh, core

    - name: "chrisvanmeer.zsh : Create {{ zsh_aliases_path }} file if needed."
      file:
        path: "{{ zsh_aliases_path }}"
        state: touch
      become: false
      when: not zsh_aliases_status.stat.exists
      tags: zsh, core

    - name: "chrisvanmeer.zsh : Add aliases to {{ zsh_aliases_path }}."
      lineinfile:
        dest: "{{ zsh_aliases_path }}"
        line: 'alias {{ item.alias }}="{{ item.command }}"'
        regexp: "^alias {{ item.alias }}="
      become: false
      loop: "{{ zsh_aliases }}"
      tags: zsh, core

    - name: "chrisvanmeer.zsh : Get zsh path."
      command: which zsh
      register: zsh_path
      become: false
      changed_when: false
      tags: zsh, core

    - name: "chrisvanmeer.zsh : Switch shell to zsh."
      user:
        name: "{{ current_user }}"
        shell: "{{ zsh_path.stdout }}"
      when: ansible_user_shell != zsh_path.stdout
      tags: zsh, core

    - name: "chrisvanmeer.dotfiles : Copy dotfiles to their location."
      copy:
        src: "{{ src_files }}/{{ item }}"
        dest: "{{ home_path }}/{{ item }}"
      become: false
      loop: "{{ dotfiles_files }}"
      tags: dotfiles, core

    - name: "chrisvanmeer.vim : Check if vim cobalt theme is present."
      stat:
        path: "{{ home_path }}/.vim/colors/cobalt.vim"
      become: false
      register: vimcolors
      tags: vim, vimcolors, core

    - name: "chrisvanmeer.vim : Ensure vim colors directory is present."
      file:
        path: "{{ home_path }}/.vim/colors"
        state: directory
      become: false
      tags: vim, vimcolors, core

    - name: "chrisvanmeer.vim : Install cobalt theme if not present."
      copy:
        src: "{{ src_files }}/.vim/colors/cobalt.vim"
        dest: "{{ home_path }}/.vim/colors/cobalt.vim"
      become: false
      when: not vimcolors.stat.exists
      tags: vim, vimcolors, core

    - name: "chrisvanmeer.vim : Check if indentLine plugin is installed."
      stat:
        path: "{{ home_path }}/.vim/pack/vendor/start/indentLine"
      become: false
      register: identline
      tags: vim, core

    - name: "chrisvanmeer.vim : Clone indentLine repo if identLine is not installed."
      git:
        repo: https://github.com/Yggdroot/indentLine.git
        dest: "{{ home_path }}/.vim/pack/vendor/start/indentLine"
      become: false
      when: not identline.stat.exists
      tags: vim, core

    - name: "chrisvanmeer.vim : Register identLine plugin if identLine is not installed."
      command: "vim -u NONE -c \"helptags {{ home_path }}/.vim/pack/vendor/start/indentLine/doc\" -c \"q\""
      become: false
      when: not identline.stat.exists
      tags: vim, core

    - name: "chrisvanmeer.php-post : Remove standard index.html."
      file:
        path: /var/www/html/index.html
        state: absent
      tags: php-post, core

    - name: "chrisvanmeer.php-post : Create Hello World PHP page."
      copy:
        dest: /var/www/html/index.php
        content: |
          <?php
            echo 'Hello World!';
          ?>
      tags: php-post, core

    - name: "chrisvanmeer.apt-pre : Add needed PPA's."
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop: "{{ ppa_repos }}"
      tags: apt-pre

    - name: "chrisvanmeer.chrome: Ensure that Google signing key is present."
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present
      tags: chrome

    - name: "chrisvanmeer.chrome : Add specified repository for Google Chrome."
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
      tags: chrome

    - name: "chrisvanmeer.chrome : Esnure only the right architecture in the repo is enabled."
      lineinfile:
        dest: /etc/apt/sources.list.d/google-chrome.list
        line: '#deb http://dl.google.com/linux/chrome/deb/ stable main'
        regexp: '^deb http'
      tags: chrome

    - name: "chrisvanmeer.xtra : Update apt cache."
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: xtra

    - name: "chrisvanmeer.xtra : Install the extra apt packages."
      apt:
        name: "{{ xtra_apt_packages }}"
        state: present
      tags: xtra

    - name: "chrisvanmeer.xtra : Install the extra snap packages."
      snap:
        name: "{{ xtra_snap_packages }}"
        classic: yes
        state: present
      tags: xtra, snap

    - name: "chrisvanmeer.xtra : Install the extra snap packages with classic parameter."
      snap:
        name: "{{ xtra_classic_snap_packages }}"
        classic: yes
        state: present
      tags: xtra, snap-classic

    - name: "chrisvanmeer.apt-post : Upgrade all apt packages."
      apt:
        upgrade: dist
        update_cache: yes
      tags: apt-post

    - name: "chrisvanmeer.apt-post : Autoremove unused apt packages."
      apt:
        autoremove: yes
      tags: apt-post

    - name: "chrisvanmeer.apt-post : Autoclean apt."
      apt:
        autoclean: yes
      tags: apt-post

    - name: "chrisvanmeer.post : Check if a reboot is needed."
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
      tags: post

  post_tasks:
    - name: "chrisvanmeer.post : Reboot warning if needed."
      debug:
        msg: "Please reboot your system"
      when: reboot_required_file.stat.exists
      tags: post
