---
- hosts: localhost
  connection: local
  become: true

  vars:
    apache_listen_ip: "127.0.0.1"

    php_version: "8.0"
    php_packages:
      - php
      - php-cli
      - libapache2-mod-php8.0

    firewall_allowed_tcp_ports:
      - "22"
      
    ntp_timezone: "Europe/Amsterdam"

    extra_packages:
      - alpine
      - apticron
      - atop
      - bsdgames
      - build-essential
      - certbot
      - curl
      - ddgr
      - git
      - googler
      - htop
      - less
      - lynx
      - mailutils
      - nano
      - net-tools
      - nload
      - telnet
      - vim
      - wget

  roles:
    - role: geerlingguy.apache
      tags: apache
    - role: geerlingguy.php-versions
      tags: php
    - role: geerlingguy.php
      tags: php
    - role: geerlingguy.php-mysql
      tags: php
    - role: geerlingguy.mysql
      tags: mysql
    - role: geerlingguy.docker
      tags: docker
    - role: geerlingguy.postfix
      tags: postfix
    - role: geerlingguy.security
      tags: security
    - role: geerlingguy.firewall
      tags: firewall
    - role: geerlingguy.ntp
      tags: ntp

  tasks:
    - name: Hush all the login banner stuff
      file:
        path: ~/.hushlogin
        state: touch
      become: false
      tags: hush

    - name: Install the extra packages
      apt:
        name: "{{ extra_packages }}"
        state: present
      tags: extra

    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
      tags: apt

    - name: Autoclean apt
      apt:
        autoclean: yes
      tags: apt
        
    - name: Autoremove apt
      apt:
        autoremove: yes
      tags: apt

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
        get_md5: no
      tags: post
      
    - name: Reboot warning if needed
      debug:
        msg: "Please reboot your system"
      when: reboot_required_file.stat.exists
      tags: post
